export const TABLE_SCHEMA = {
  id: '5d91e2c5654e8ab86af4a570',
  name: 'tableName',
  fields: [
    {
      id: '5d95f05f1aa40e0662f298e3',
      name: 'id',
      displayName: 'ID',
      description: null,
      fieldType: 'ID',
      fieldTypeAttributes: null,
      isList: false,
      isRequired: true,
      isUnique: true,
      defaultValue: null,
      isSystem: true,
      isMeta: true,
      relation: null,
      schemaFeatures: {
        update: false,
        delete: false,
      },
      dataFeatures: {
        create: false,
        update: false,
      },
    },
    {
      id: '5d95f05f1aa40ee167f298e4',
      name: 'createdAt',
      displayName: 'Created At',
      description: null,
      fieldType: 'DATE',
      fieldTypeAttributes: {
        format: 'DATETIME',
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: true,
      isMeta: true,
      relation: null,
      schemaFeatures: {
        update: false,
        delete: false,
      },
      dataFeatures: {
        create: false,
        update: false,
      },
    },
    {
      id: '5d95f05f1aa40e3eb4f298e7',
      name: 'updatedAt',
      displayName: 'Updated At',
      description: null,
      fieldType: 'DATE',
      fieldTypeAttributes: {
        format: 'DATETIME',
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: true,
      isMeta: true,
      relation: null,
      schemaFeatures: {
        update: false,
        delete: false,
      },
      dataFeatures: {
        create: false,
        update: false,
      },
    },
    {
      id: '5d95f05f1aa40efe66f298ed',
      name: 'createdBy',
      displayName: 'Created By',
      description: null,
      fieldType: 'RELATION',
      fieldTypeAttributes: null,
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: true,
      isMeta: true,
      relation: null,
      schemaFeatures: {
        update: false,
        delete: false,
      },
      dataFeatures: {
        create: false,
        update: false,
      },
    },
    {
      id: '5d95f06b1aa40e1102f29b16',
      name: 'dateField',
      displayName: 'Date Field',
      description: null,
      fieldType: 'DATE',
      fieldTypeAttributes: {
        format: 'DATE',
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f0771a9b575e44e40e50',
      name: 'datetimeField',
      displayName: 'Datetime Field',
      description: null,
      fieldType: 'DATE',
      fieldTypeAttributes: {
        format: 'DATETIME',
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f0a11a9b579ae8e412b6',
      name: 'intField',
      displayName: 'Int Field',
      description: null,
      fieldType: 'NUMBER',
      fieldTypeAttributes: {
        format: 'NUMBER',
        precision: 0,
        currency: null,
        minValue: 10,
        maxValue: 2000,
        isBigInt: null,
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f0b91a9b57b978e417b8',
      name: 'numberField',
      displayName: 'Number Field',
      description: null,
      fieldType: 'NUMBER',
      fieldTypeAttributes: {
        format: 'NUMBER',
        precision: 4,
        currency: null,
        minValue: null,
        maxValue: null,
        isBigInt: null,
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f0e81aa40e6bebf29c37',
      name: 'switchField',
      displayName: 'Switch Field',
      description: null,
      fieldType: 'SWITCH',
      fieldTypeAttributes: {
        format: 'ON_OFF',
        listOptions: null,
      },
      isList: false,
      isRequired: false,
      isUnique: null,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f0fa1aa40e1ae1f2a141',
      name: 'text',
      displayName: 'Text',
      description: null,
      fieldType: 'TEXT',
      fieldTypeAttributes: {
        format: 'UNFORMATTED',
        fieldSize: 100,
      },
      isList: false,
      isRequired: false,
      isUnique: false,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
    {
      id: '5d95f2211a9b57752ee425bf',
      name: 'customSwitch',
      displayName: 'Custom Switch',
      description: null,
      fieldType: 'SWITCH',
      fieldTypeAttributes: {
        format: 'CUSTOM',
        listOptions: ['foo', 'bar', 'buz'],
      },
      isList: false,
      isRequired: false,
      isUnique: null,
      defaultValue: null,
      isSystem: false,
      isMeta: false,
      relation: null,
      schemaFeatures: {
        update: true,
        delete: true,
      },
      dataFeatures: {
        create: true,
        update: true,
      },
    },
  ],
};
